export const surpriseMePrompts = [
  'a cozy reading nook with a large window overlooking a snowy forest',
  'a grandmother baking cookies with her grandchildren in a warm, rustic kitchen',
  'a black-and-white photograph of a jazz band performing in a smoky club',
  'a serene sunrise over a misty lake, with a lone fisherman in a small boat',
  'a close-up of a bee pollinating a sunflower in a vibrant summer garden',
  'a bustling farmers market in a European town square, with colorful stalls and fresh produce',
  'a young couple dancing in the rain on a cobblestone street at dusk',
  'a realistic oil painting of a cat curled up by a crackling fireplace',
  'a classic car parked in front of a retro diner, with neon lights glowing at night',
  'a family enjoying a picnic in a sunlit meadow filled with wildflowers',
  'a detailed sketch of an old library with towering shelves filled with books',
  'a serene beach scene with gentle waves and a hammock strung between two palm trees',
  'a close-up of a violinist’s hands as they play a melancholic tune',
  'a cityscape at dawn, with the first light reflecting off tall glass buildings',
  'a winter scene of children ice skating on a frozen pond, with snow-covered trees in the background',
  'a gourmet dinner being served at an elegant outdoor restaurant under twinkling lights',
  'a tranquil forest trail with dappled sunlight filtering through the leaves',
  'a mother and child planting flowers in a garden on a sunny spring day',
  'a fisherman casting a line into a calm river as the sun sets behind him',
  'a bustling coffee shop with patrons sipping drinks and chatting on a rainy day',
  'a detailed watercolor painting of a Mediterranean village with white-washed houses and narrow streets',
  'a candid photo of an elderly couple holding hands while walking through a park',
  'a chef preparing a meal in a modern kitchen with fresh ingredients laid out on the counter',
  'a peaceful night sky filled with stars, with a silhouette of mountains in the distance',
  'a child playing with a puppy in a backyard filled with autumn leaves',
  'a black-and-white portrait of an artist at work in their studio, surrounded by canvases and paint',
  'a mountain cabin surrounded by tall pines, with smoke rising from the chimney',
  'a group of friends gathered around a campfire, roasting marshmallows under the night sky',
  'a bustling street market in Marrakech, with vibrant textiles and spices on display',
  'a couple enjoying a candlelit dinner on a balcony overlooking a city skyline at night',
  'a serene garden with a koi pond, stone lanterns, and a small wooden bridge',
  'a detailed drawing of a vintage typewriter with a blank sheet of paper ready for writing',
  'a rainy day scene of people huddled under umbrellas as they walk down a busy city street',
  'a close-up of a barista pouring a latte art heart into a cup of coffee',
  'a sunset view from the deck of a sailboat, with the ocean stretching out to the horizon',
  'a father teaching his son how to ride a bicycle on a quiet suburban street',
  'a street performer playing the saxophone on a Parisian bridge at twilight',
  'a colorful bird perched on a branch in a dense tropical rainforest',
  'a group of children flying kites on a breezy summer day in a large open field',
  'a traditional Japanese tea ceremony taking place in a minimalist room',
  'a dog lying contentedly by the door, waiting for its owner to return home',
  'a scenic overlook of a mountain range with a hiker taking in the view at sunrise',
  'a photo of a quaint bakery displaying fresh pastries and bread in the window',
  'a grandmother knitting a scarf by the window while a cat sleeps at her feet',
  'a lively street festival with colorful banners, food stalls, and live music',
  'a tranquil zen garden with perfectly raked sand and carefully placed rocks',
  'a photo of a sunrise over the ocean with seagulls flying in the distance',
  'a rustic cabin in the woods, with a firepit outside and smoke rising from the chimney',
  'a family gathering around the dinner table for a holiday meal, with laughter and conversation filling the air',
];
